update readme.txt
woocommerce/woocommerce-paypal-payments pull request #1667
Opened 2023-09-05 09:19 UTC by InpsydeNiklas

updates the readme.txt

2023-09-05 12:52 UTC, Dinamiko requested changes

2023-09-05 12:52 UTC, Dinamiko commented on readme.txt
> += The all-in-one checkout solution* =
Is asterisk intented here? `solution*`

2023-09-05 12:52 UTC, Dinamiko commented on readme.txt
> +\*For Australian users, the PayPal service is provided by PayPal Australia Pty Limited AFSL 304962. Any information provided is general only and does not take into account your objectives, financial
Seems `\*` is not needed here,  can you please confirm?

2023-09-05 12:52 UTC, Dinamiko commented on readme.txt
> +
Seems this new line is not needed here, doesn't it?

2023-09-05 13:10 UTC, InpsydeNiklas commented on readme.txt
> += The all-in-one checkout solution* =
This relates to the legal disclosures below.

2023-09-05 13:10 UTC, InpsydeNiklas commented on readme.txt
> +\*For Australian users, the PayPal service is provided by PayPal Australia Pty Limited AFSL 304962. Any information provided is general only and does not take into account your objectives, financial
This `\` is needed to nullify the `*` which relates to the above.

2023-09-05 13:11 UTC, InpsydeNiklas commented on readme.txt
> +
This section is subject to change, so it should be fine for now.

2023-09-08 13:35 UTC, Dinamiko approved these changes

2023-09-13 12:03 UTC, merged