Make PayPal Subscription products unique in cart (2566)
woocommerce/woocommerce-paypal-payments pull request #2265
Opened 2024-05-27 13:01 UTC by burdulixda

### Description

If there is a PayPal Subscription product in the cart, that can be the _only_ product in the cart.

### Steps to Test

1. Add a PayPal Subscription product in the cart;
2. Try to add another product in the cart;
3. The error notice should appear prompting the user that PayPal subscription should be a unique item in the cart;
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/46271505/2f4cfa85-f729-4079-8586-f69c0add4c7f)

2024-05-28 10:17 UTC, Dinamiko requested changes

2024-05-28 10:17 UTC, Dinamiko commented on modules/ppcp-paypal-subscriptions/src/PayPalSubscriptionsModule.php
> +					if ( get_post_meta( $cart_item['product_id'], 'ppcp_subscription_product', true ) ) {
Better use [WC Data API for product meta](https://github.com/woocommerce/woocommerce-paypal-payments/blob/trunk/modules/ppcp-paypal-subscriptions/src/SubscriptionsApiHandler.php#L141), it's more future proof, if WC decides to change how it works internally in the future we don't care as we follow the API contract.

2024-05-29 09:35 UTC, Dinamiko requested changes

2024-05-29 09:35 UTC, Dinamiko commented on modules/ppcp-paypal-subscriptions/src/PayPalSubscriptionsModule.php
> +					update_metadata( 'post', $product->get_id(), '_sold_individually', 'yes', 'no' );
Better use WC Product API to [set sold individually](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/abstracts/abstract-wc-product.php#L1013-L1015):

![Captura de pantalla 2024-05-29 a las 11 28 10](https://github.com/woocommerce/woocommerce-paypal-payments/assets/456223/cc51b0fa-4e8c-4525-9cc7-cc1ba1e1d6bb)

2024-05-29 10:47 UTC, Dinamiko approved these changes

2024-05-30 11:27 UTC, burdulixda reviewed
@Dinamiko I had to also add "set_sold_individually()" function during add to cart validation because some users may never update their products manually

2024-05-30 12:05 UTC, Dinamiko approved these changes

2024-05-31 07:49 UTC, merged