Default UI: Legacy for existing merchants, React for new merchants (4030)
woocommerce/woocommerce-paypal-payments pull request #2936
Opened 2024-12-19 11:58 UTC by Narek13

# Issue Description

**Current situation**
When the feature flag for the new UI is enabled, all merchants instantly see the new onboarding wizard and settings screens.

 **Expected**
- When the feature flag is enabled, existing merchants should still get the legacy settings UI, with a new button/toggle to enable the new UI.
  - Those users should not see the onboarding wizard, but directly get the settings pages
- All new merchants (i.e. fresh installations) should instantly see the new UI, starting with the onboarding wizard.

# PR Description

The PR will cover the following scenarios when the feature flag for the new UI is enabled:

- All the new merchants (i.e. fresh installations) will instantly see the new UI, starting with the onboarding wizard.
- existing merchants will still get the legacy settings UI, with a new button/toggle to enable the new UI.
  -  If onboarded, will not see the onboarding wizard, but directly get the settings pages

2025-01-03 13:17 UTC, danieldudzic requested changes
@Narek13 Looking good!

I have noticed that when I select the "Switch to new settings UI" button, it doesn't do anything, and throws an error in the console:
<img width="1395" alt="WooCommerce_settings_‹_WooCommerce_PayPal_Payments_—_WordPress_i_Bring_Me_The_Horizon_-_The_House_of_Wolves_i_a-team__Channel__-_Syde_-_Slack" src="https://github.com/user-attachments/assets/0e5dcc29-b007-4bc5-b1da-4e48943f00db" />

The page correctly then displays the new settings UI, after a page reload.

The new UI should show up straight after selecting the button.

2025-01-07 08:49 UTC, Narek13 commented
@danieldudzic I cannot reproduce, works fine for me, once clicked on the button, the page reloads with the new settings. Did you build the scripts? Maybe someone else also can check this.

2025-01-09 11:20 UTC, danieldudzic commented
@Narek13 Ok, I have now identified the issue. With `WP_DEBUG` active it was being caused by: https://github.com/woocommerce/woocommerce-paypal-payments/pull/2816

<img width="1374" alt="WooCommerce_settings_‹_WooCommerce_PayPal_Payments_—_WordPress_i_pokaż__wp_options_-_AdminerEvo" src="https://github.com/user-attachments/assets/df5e9dc7-7494-45b9-8a10-bfee783ad23c" />

2025-01-09 11:20 UTC, danieldudzic approved these changes
All good!

2025-01-23 09:55 UTC, merged