New Settings UI: Disable settings in send-only countries (4027)
woocommerce/woocommerce-paypal-payments pull request #2937
Opened 2024-12-19 13:41 UTC by hmouhtar

### Description

This PR updates the settings screen to hide all settings if the store's current country is classified as a send-only country. Instead, a message explaining this limitation will be displayed.

### Steps to Test

1. Enable the new settings UI
2. Set the WooCommerce store country to one that is within the send-only list. This list can be found in [PCP-3970](https://inpsyde.atlassian.net/browse/PCP-3790).
3. Verify that no settings appear on the PayPal settings screen. Instead, a message explaining this limitation should be displayed.

### Screenshots

![WooCommerce-settings-‹-WooCommerce-PayPal-Payments-—-WordPress-12-19-2024_02_41_PM](https://github.com/user-attachments/assets/1b72c06d-2860-4e93-b177-7ae778dd5488)

2024-12-19 13:43 UTC, hmouhtar commented
@stracker-phil I wasn’t sure if there is a specific style we need to use for notices, so I haven’t added any styling for the notice yet, just plain text.

2024-12-20 15:20 UTC, stracker-phil commented on modules/ppcp-settings/resources/js/Components/Screens/SendOnlyMessage.js
We should translate this message via `__()` or inject the string from server-side using `wp_localize_script()`

2024-12-20 15:21 UTC, stracker-phil requested changes
Localization is missing 😉

2024-12-26 13:10 UTC, hmouhtar commented on modules/ppcp-settings/resources/js/Components/Screens/SendOnlyMessage.js
Hi @stracker-phil, I added localization to the message in my latest commit 👍🏻

2025-01-08 17:59 UTC, stracker-phil requested changes

2025-01-08 17:59 UTC, stracker-phil commented on modules/ppcp-paylater-configurator/src/PayLaterConfiguratorModule.php
> +				$onboarding_state    = $c->get( 'onboarding.state' );
This uses the legacy onboarding status.

To check if the onboarding in the new UI is completed, you can use this logic:

```php
$onboarding_profile = $c->get( 'settings.data.onboarding' );
$onboarding_profile->get_completed(); // true = onboarding is done, false = still in the onboarding wizard
```

2025-01-10 12:35 UTC, hmouhtar commented on modules/ppcp-paylater-configurator/src/PayLaterConfiguratorModule.php
> +				$onboarding_state    = $c->get( 'onboarding.state' );
Hi @stracker-phil, I've switched to the new onboarding profile class on my latest commit 👍🏻

2025-01-10 18:17 UTC, stracker-phil approved these changes

2025-01-10 20:12 UTC, merged