New Settings UI: Remove section links from PayPal settings page (4049)
woocommerce/woocommerce-paypal-payments pull request #2956
Opened 2024-12-30 21:02 UTC by hmouhtar

### Description

Some plugins, such as [WooPayments](https://es.wordpress.org/plugins/woocommerce-payments/), may add extra sections to the checkout tab . By default, WooCommerce outputs the links to these sections at the beginning of the tab. 

To prevent these section links from displaying on the PayPal settings page, this PR takes care of removing the action responsible of echoing the links. 

### Steps to Test

1. Enable the new PayPal settings UI
2. [Install the WooCommerce Payments plugin](https://es.wordpress.org/plugins/woocommerce-payments/)
3. Go to the Payments tab inside the WooCommerce settings page.
4. Verify that there are 2 links at the top: "WooPayments" and "All payment methods".
5. Go to the PayPal settings section.
6. Verify that the 2 links are not displaying.

It might be worth moving the logic for removing an action based on its name to a separate function, which could be useful in future cases like this one, where we don't have access to a class instance to remove an action or filter directly.

2025-01-08 17:47 UTC, stracker-phil requested changes
Nice solution, technically it looks good.

Just 2 small things:
1. Since it's such a technical bit, I would be much happier if there was a short comment above the add_action() giving a short hint on why we're removing items from the global `$wp_filter` array here 😉
2. Psalm complains about line 228. Maybe a different check works better? I'd try this: `$function[0] instanceof WC_Settings_Payment_Gateways`

2025-01-08 19:01 UTC, Narek13 commented on modules/ppcp-settings/src/SettingsModule.php
> +				}
Why not having like this?

```suggestion
				if ( 
					! $container->has( 'wcgateway.is-ppcp-settings-page' )
					|| ! $container->get( 'wcgateway.is-ppcp-settings-page' )
					|| empty( $wp_filter['woocommerce_sections_checkout']->callbacks )
				) {
					return;
				}
```

2025-01-08 19:02 UTC, Narek13 approved these changes
Thanks for working on this. Just a minor suggestion which you can ignore

2025-01-10 12:03 UTC, hmouhtar commented on modules/ppcp-settings/src/SettingsModule.php
> +				}
@Narek13  I've moved the declaration of `$wp_filter` after the first check as suggested. Thanks 🙂

2025-01-10 12:15 UTC, Narek13 approved these changes

2025-01-13 13:50 UTC, stracker-phil approved these changes

2025-01-20 14:02 UTC, stracker-phil approved these changes

2025-01-20 14:26 UTC, stracker-phil commented
Though this solution works, I think a **CSS-only solution** aligns better with the current setup and keeps the codebase cleaner (all UI adjustments are currently done via CSS, this would be the first UI cleanup that's done via PHP)

I've added a new PR that provides the relevant CSS changes to hide the extra menu items: #3008

2025-01-28 10:13 UTC, stracker-phil commented
Closing this in favor of #3008

2025-01-28 10:13 UTC, closed without merging